### ISSUE TITLE
关于FTP的配置

### ISSUE THREAD

**Issue by AtomRun** [qiuxinfa/springboot-shiro-vue-stu#9]
请问作者关于FTP的使用，有相关介绍吗？直接看代码，有点不太明白FTP这里怎么使用的。。

**Comment by qiuxinfa** [comment]
我是参考这两篇博客弄的：
（1）https://blog.csdn.net/qq_44697035/article/details/96481448
（2）https://www.cnblogs.com/liangxuru/p/6148212.html

**Comment by AtomRun** [comment]
> 我是参考这两篇博客弄的：
> （1）https://blog.csdn.net/qq_44697035/article/details/96481448
> （2）https://www.cnblogs.com/liangxuru/p/6148212.html

谢谢！
